# Generated by Django 4.2 on 2023-04-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('number_of_pages', models.PositiveIntegerField()),
                ('summary', models.TextField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
