# Generated by Django 4.2 on 2023-04-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_surname', models.CharField(max_length=100, verbose_name='Adı Soyadı')),
                ('identity_number', models.BigIntegerField(verbose_name='T.C Kimlik No')),
                ('phone_number', models.BigIntegerField(verbose_name='Cep Telefonu')),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
