# Generated by Django 4.2 on 2023-04-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
    ]
