# Generated by Django 4.2 on 2023-04-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_book_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarrowedBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
