# Generated by Django 4.2 on 2023-04-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_barrowedbook_book_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrowedbook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
