# Generated by Django 4.2 on 2023-04-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_barrowedbook_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_surname', models.CharField(max_length=100, verbose_name='Adı Soyadı')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='barrowedbook',
            name='is_returned',
            field=models.BooleanField(auto_created=True, default=False),
        ),
    ]
