# Generated by Django 4.2 on 2023-04-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_user_barrowedbook_is_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrowedbook',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
