# Generated by Django 4.2 on 2023-04-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_barrowedbook_is_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrowedbook',
            name='is_returned',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
